import type { BespokeJobOrder } from '../types/workshop.types';

/**
 * First-run / offline fallback demo data — used by ClientOrderTracker when
 * Supabase is unreachable and there's no offline cache yet. Also reused by
 * tests that need a handful of realistic bespoke orders.
 */
export const SEED_WORKSHOP_ORDERS: BespokeJobOrder[] = [
  {
    id: 'ORD-BESPOKE-884',
    clientName: 'Dr. Esi Sutherland',
    clientPhone: '0244123456',
    stage: 'pending',
    garmentTitle: 'Ashanti Royal Silk Corset Gown',
    garmentSubtitle: 'State Banquet Evening Wear',
    fabricType: 'Handwoven Indigo & Gold Silk Kente',
    fabricColor: 'Royal Gold & Midnight Indigo',
    fabricNotes: 'Reinforced waist boning with gold thread embroidery along neckline.',
    referenceImages: [
      '/shop/kente_corset.png',
      '/shop/adinkra_gown.png',
      '/editorial.png',
    ],
    swatchImage: '/shop/kente_corset.png',
    measurements: {
      clientId: 'cli-884',
      clientName: 'Dr. Esi Sutherland',
      clientPhone: '0244123456',
      unit: 'in',
      values: { bust: 34.5, waist: 26.8, hips: 38.2, shoulder: 15.5, sleeve_length: 24.0, neck_to_waist: 16.0 },
      updatedAt: '2026-08-08T10:30:00Z',
    },
    depositPaid: 1725,
    totalAmount: 3450,
    assignedTailor: 'Master Kwame Mensah',
    dueDate: 'AUG 18, 2026',
    createdAt: '2026-08-08T09:15:00Z',
    tasks: [
      {
        id: 'tsk-01',
        orderId: 'ORD-BESPOKE-884',
        tailorName: 'Master Kwame Mensah',
        title: 'Draft master pattern & cut silk lining',
        status: 'completed',
        assignedAt: '2026-08-08T10:00:00Z',
        completedAt: '2026-08-08T14:30:00Z',
      },
      {
        id: 'tsk-02',
        orderId: 'ORD-BESPOKE-884',
        tailorName: 'Artisan Kofi Badu',
        title: 'Stitch structural corset boning channels',
        status: 'in_progress',
        assignedAt: '2026-08-08T15:00:00Z',
      },
    ],
    stageHistory: [
      {
        stage: 'pending',
        completedAt: '2026-08-08T09:15:00Z',
        completedBy: 'Receptionist Abena',
        notes: 'Deposit received. Job card created.',
      },
    ],
  },
  {
    id: 'ORD-BESPOKE-889',
    clientName: 'Hon. Kofi Annan-Prah',
    clientPhone: '0549876543',
    stage: 'cutting',
    garmentTitle: '3-Piece Northern Fugu Tuxedo',
    garmentSubtitle: 'Diplomatic Gala Commission',
    fabricType: 'Heavyweight Striped Cotton Fugu',
    fabricColor: 'Monochrome Charcoal & Ivory',
    fabricNotes: 'Full canvas construction with silk satin lapel contrast.',
    referenceImages: [
      '/shop/fugu_blazer.png',
      '/editorial.png',
    ],
    swatchImage: '/shop/fugu_blazer.png',
    measurements: {
      clientId: 'cli-889',
      clientName: 'Hon. Kofi Annan-Prah',
      clientPhone: '0549876543',
      unit: 'in',
      values: { bust: 42.0, waist: 34.0, hips: 43.5, shoulder: 18.5, sleeve_length: 26.0, neck_to_waist: 18.0 },
      updatedAt: '2026-08-07T14:00:00Z',
    },
    depositPaid: 2100,
    totalAmount: 4200,
    assignedTailor: 'Artisan Kofi Badu',
    dueDate: 'AUG 20, 2026',
    createdAt: '2026-08-07T11:00:00Z',
    tasks: [],
    stageHistory: [
      {
        stage: 'pending',
        completedAt: '2026-08-07T11:00:00Z',
        completedBy: 'Receptionist Abena',
        notes: '50% MoMo deposit confirmed.',
      },
      {
        stage: 'cutting',
        completedAt: '2026-08-08T08:30:00Z',
        completedBy: 'Artisan Kofi Badu',
        notes: 'Fabric inspected and pattern laid out.',
      },
    ],
  },
  {
    id: 'ORD-BESPOKE-891',
    clientName: 'Nana Akosua Frimpong',
    clientPhone: '0201122334',
    stage: 'fitting',
    garmentTitle: 'Adinkra Embroidered Couture Peplum Gown',
    garmentSubtitle: 'Executive Induction Ceremony',
    fabricType: 'Crimson Silk Mikado with Velvet Adinkra Emblems',
    fabricColor: 'Rich Crimson & Obsidian Velvet',
    fabricNotes: 'Gya Nyame gold bullion hand-embroidery on cuffs and neckline.',
    referenceImages: [
      '/shop/adinkra_gown.png',
      '/editorial.png',
    ],
    swatchImage: '/shop/adinkra_gown.png',
    measurements: {
      clientId: 'cli-891',
      clientName: 'Nana Akosua Frimpong',
      clientPhone: '0201122334',
      unit: 'in',
      values: { bust: 37.0, waist: 29.5, hips: 41.0, shoulder: 16.0, sleeve_length: 23.5, neck_to_waist: 16.5 },
      updatedAt: '2026-08-05T16:00:00Z',
    },
    depositPaid: 2600,
    totalAmount: 5200,
    assignedTailor: 'Master Kwame Mensah',
    dueDate: 'AUG 15, 2026',
    createdAt: '2026-08-05T12:00:00Z',
    tasks: [],
    stageHistory: [
      {
        stage: 'pending',
        completedAt: '2026-08-05T12:00:00Z',
        completedBy: 'System',
        notes: 'Order initiated.',
      },
      {
        stage: 'cutting',
        completedAt: '2026-08-06T10:00:00Z',
        completedBy: 'Master Kwame Mensah',
        notes: 'Silk cut.',
      },
      {
        stage: 'fitting',
        completedAt: '2026-08-08T15:00:00Z',
        completedBy: 'Master Kwame Mensah',
        notes: 'Preliminary toile assembled for first lounge fitting.',
      },
    ],
  },
  {
    id: 'ORD-BESPOKE-895',
    clientName: 'Kweku Boateng Esq.',
    clientPhone: '0275566778',
    stage: 'finishing',
    garmentTitle: 'Modern Double-Breasted Kente Blazer',
    garmentSubtitle: 'Architectural Heritage Suit',
    fabricType: 'Geometric Gold Silk/Cotton Blend',
    fabricColor: 'Sahara Ochre & Earth Brown',
    fabricNotes: 'Hand-sewn pick stitching and horn buttons.',
    referenceImages: [
      '/shop/fugu_blazer.png',
      '/editorial.png',
    ],
    swatchImage: '/shop/fugu_blazer.png',
    measurements: {
      clientId: 'cli-895',
      clientName: 'Kweku Boateng Esq.',
      clientPhone: '0275566778',
      unit: 'in',
      values: { bust: 40.0, waist: 32.5, hips: 40.0, shoulder: 17.5, sleeve_length: 25.5, neck_to_waist: 17.0 },
      updatedAt: '2026-08-04T10:00:00Z',
    },
    depositPaid: 1900,
    totalAmount: 3800,
    assignedTailor: 'Artisan Ama Frimpong',
    dueDate: 'AUG 12, 2026',
    createdAt: '2026-08-04T09:00:00Z',
    tasks: [],
    stageHistory: [],
  },
  {
    id: 'ORD-BESPOKE-872',
    clientName: 'Lady Beatrice Osei',
    clientPhone: '0551239876',
    stage: 'ready',
    garmentTitle: 'Hand-Pleated Kente Mermaid Gown',
    garmentSubtitle: 'Diplomatic Gala',
    fabricType: 'Vintage 1970s Restored Silk Kente',
    fabricColor: 'Emerald Green & Gold Thread',
    fabricNotes: 'Dry clean only. Packed in velvet garment bag.',
    referenceImages: [
      '/shop/kente_corset.png',
      '/editorial.png',
    ],
    swatchImage: '/shop/kente_corset.png',
    measurements: {
      clientId: 'cli-872',
      clientName: 'Lady Beatrice Osei',
      clientPhone: '0551239876',
      unit: 'in',
      values: { bust: 35.0, waist: 27.0, hips: 39.0, shoulder: 15.0, sleeve_length: 23.0, neck_to_waist: 15.5 },
      updatedAt: '2026-08-01T11:00:00Z',
    },
    depositPaid: 4500,
    totalAmount: 4500,
    assignedTailor: 'Master Kwame Mensah',
    dueDate: 'AUG 10, 2026',
    createdAt: '2026-08-01T10:00:00Z',
    tasks: [],
    stageHistory: [],
  },
];
